### ISSUE TITLE
起動完了変数がtrueにならない

### ISSUE THREAD

**Issue by gx1285** [aqued-dev/aqued#85]
恐らくこれが原因
```js
TypeError: Cannot read properties of undefined (reading 'isThread')
    at Object.execute (file:///home/aqued/aqued/dist/src/events/ClientReady.js:28:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (file:///home/aqued/aqued/dist/src/index.js:134:77)
```

**Comment by gx1285** [comment]
v3 not supported
